### ISSUE TITLE
Modal subtitle2 retains previous content

### ISSUE THREAD

**Issue by Stick1000** [upvkomsai/upvkomsai.github.io#17]
When launching a modal, this happens.
![image](https://user-images.githubusercontent.com/28281336/128361608-2db761da-3a55-418d-a5eb-4d2f040addbe.png)
But when opening a modal at the gallery, since there is no `subtitle2` property on the gallery item, it is not overwritten.
![image](https://user-images.githubusercontent.com/28281336/128361756-ef0d3b0f-fafd-458c-8f98-683e9763efaf.png)

**Comment by jvc1019** [comment]
After some commits, it now does the opposite.

Opening a card that is not an Officer, then opening an Officer card would make it lose the email on the modal.
