### ISSUE TITLE
404 page not working properly.

### ISSUE THREAD

**Issue by cjfaeldonea** [upvkomsai/upvkomsai.github.io#6]
![image](https://user-images.githubusercontent.com/72564347/127323304-d59327be-69a9-4ef3-8b26-e56ad89e4226.png)

It caught several wrong URLs however, the page design and layout is damaged.

Definition of Done:

- [x] 404 Error page behaves properly for both desktop and mobile views
- [x] Fixed design for the page.

**Comment by jvc1019** [comment]
Error 404 page now works for Desktop, yet not for mobile.
